// This file is generated by scripts/generate-pavillion-media.mjs.
// Add media to public/pavillion, then run npm run media:sync.

export const pavillionMedia = {
  "bingo16may": [
    "/pavillion/bingo16may_v1.png",
    "/pavillion/bingo16may_v2.png",
    "/pavillion/bingo16may_v3.png",
    "/pavillion/bingo16may_v4.png",
    "/pavillion/bingo16may_v5.png",
    "/pavillion/bingo16may_v6.png",
    "/pavillion/bingo16may_v7.png",
    "/pavillion/bingo16may_v8.png",
    "/pavillion/bingo16may_v9.png",
    "/pavillion/bingo16may_v10.png",
    "/pavillion/bingo16may_v11.png",
    "/pavillion/bingo16may_v12.png",
    "/pavillion/bingo16may_v13.png",
    "/pavillion/bingo16may_v14.png",
    "/pavillion/bingo16may_v15.png",
    "/pavillion/bingo16may_v16.png"
  ],
  "bingo23may": [
    "/pavillion/bingo23may_v1.png",
    "/pavillion/bingo23may_v2.png",
    "/pavillion/bingo23may_v3.png",
    "/pavillion/bingo23may_v4.png",
    "/pavillion/bingo23may_v5.png",
    "/pavillion/bingo23may_v6.png",
    "/pavillion/bingo23may_v7.png",
    "/pavillion/bingo23may_v8.png",
    "/pavillion/bingo23may_v9.png",
    "/pavillion/bingo23may_v10.png",
    "/pavillion/bingo23may_v11.png",
    "/pavillion/bingo23may_v12.png",
    "/pavillion/bingo23may_v13.png",
    "/pavillion/bingo23may_v14.png",
    "/pavillion/bingo23may_v15.png",
    "/pavillion/bingo23may_v16.png",
    "/pavillion/bingo23may_v17.png",
    "/pavillion/bingo23may_v18.png",
    "/pavillion/bingo23may_v19.png",
    "/pavillion/bingo23may_v20.png",
    "/pavillion/bingo23may_v21.png"
  ],
  "video02may": [
    "/pavillion/video02may_v1.png",
    "/pavillion/video02may_v2.png",
    "/pavillion/video02may_v3.png",
    "/pavillion/video02may_v4.png"
  ]
} as const;

export const pavillionUngroupedMedia = [
  "/pavillion/ploofyzlogo.jpeg",
  "/pavillion/ploofyztitle.png"
] as const;
